GET http://localhost:3001/players

###
POST http://localhost:3001/players
Content-Type: application/json

{
    "name": "player 09",
    "rank": 10 
}


###
GET http://localhost:3001/rooms

###
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "name": "room-10",
    "players": [
        "49239f79-0e7b-42fc-8b6d-0ca18f1ee21f"
    ] 
}

###
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "name": "room-11",
    "players": ["0b4e0f66-019e-407b-a209-ed74c1761f54"] 
}

###
POST http://localhost:3001/rooms/room-10/join
Content-Type: application/json

{
   "playerId": "69162b33-a09e-475a-8d1b-183ed7968fe6"
}

### 
POST http://localhost:3001/queue/start
Content-Type: application/json

{
    "name": "room-10"
}

###
POST http://localhost:3001/queue/stop
Content-Type: application/json

{
    "name": "room-10"
}


### 
POST http://localhost:3001/matches
Content-Type: application/json

{
    "roomName": "room-10",
    "playerId": "95239f79-0e7b-42fc-8b6d-0ca18f1ee21f",
    "matchId": "matchid",
    "side": "BLUE"
}