GET http://localhost:3001/players

###
POST http://localhost:3001/players
Content-Type: application/json

{
    "name": "player 09",
    "rank": 10 
}


###
GET http://localhost:3001/rooms

###
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "name": "room-10",
    "players": [
        "d8dfb5b8-d67f-4fcc-8569-fc9088cf4a48"
    ] 
}

###
POST http://localhost:3001/rooms
Content-Type: application/json

{
    "name": "room-11",
    "players": ["0b4e0f66-019e-407b-a209-ed74c1761f54"] 
}

###
POST http://localhost:3001/rooms/room-10/join
Content-Type: application/json

{
   "playerId": "69162b33-a09e-475a-8d1b-183ed7968fe6"
}

### 
POST http://localhost:3001/queue/start
Content-Type: application/json

{
    "name": "room-10"
}

###
POST http://localhost:3001/queue/stop
Content-Type: application/json

{
    "name": "room-10"
}


### 
POST http://localhost:3001/matches
Content-Type: application/json

{
    "sides": {
        "blueSide": [
            "0b4e0f66-019e-407b-a209-ed74c1761f44",
            "0b4e0f66-019e-407b-a209-ed74c1761f52",
            "0b4e0f66-019e-407b-a209-ed74c1761f53",
            "0b4e0f66-019e-407b-a209-ed74c1761f54",
            "0b4e0f66-019e-407b-a209-ed74c1761f55"
        ],
        "redSide": [
            "0b4e0f66-019e-407b-a209-ed74c1761f14",
            "0b4e0f66-019e-407b-a209-ed74c1761f24",
            "0b4e0f66-019e-407b-a209-ed74c1761f34",
            "0b4e0f66-019e-407b-a209-ed74c1761f64",
            "0b4e0f66-019e-407b-a209-ed74c1761f74"
        ]
    },
    "name": "room-10"
}